### PR TITLE
feat(gif) Add keypress to GIF Events

### PR DESCRIPTION
**Pull request by robertpin**

### CODE REVIEW

**Comment by robertpin** [comment]
Issue: #275

**Review by pshoniuk — APPROVED** [review]
LGTM

**Review by giannif — APPROVED** [review]
LGTM !

<div><br/>via <a href="https://giphy.com/joeyahlbum/">joeyahlbum</a> on <a href="https://giphy.com/gifs/animated-ok-okay-oOCbcGBJjlXJL8imGO">GIPHY</a></div>

**Comment by robertpin** [comment]
Thank you @pshoniuk and @giannif ! I have one more question: when can we expect this to be released?

**Comment by pshoniuk** [comment]
I'm going to release it later today. I'll update the status here when the release is ready.

**Pull request merged**
